spring:
  application:
    name: ProductService
  jpa:
    open-in-view:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5436/product?currentSchema=publicschema&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      mode: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
server:
  port: 8089
product:
  category: phone
redis:
  server:
    port: 6379
  address: 127.0.0.1